Updated 4-reload_gunicorn_no_downtime

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,4 +1,27 @@
 #!/usr/bin/env bash
-# Gracefully reloads Gunicorn.
+# Gracefully reloads Gunicorn
 
-ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
+
+MASTER_PID=$(pgrep -o gunicorn)
+
+if [ -z "$MASTER_PID" ]; then
+    echo "Gunicorn master process not found"
+    exit 1
+fi
+
+echo "Reloading Gunicorn with PID $MASTER_PID"
+
+kill -HUP "$MASTER_PID"
+
+sleep 5
+
+NEW_MASTER_PID=$(pgrep -o gunicorn)
+
+if [ "$MASTER_PID" != "$NEW_MASTER_PID" ]; then
+    echo "Gunicorn has been successfully reloaded."
+else
+    echo "Failed to reload Gunicorn. The process did not restart."
+    exit 1
+fi
+
+echo "Graceful reload of Gunicorn completed."
